server:
  port: 8081
  forward-headers-strategy: framework
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 307631907025-nrsq4dog0i2bg8ll8n9akuposk8deplb.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  mail:
    host: smtp.gmail.com
    port: 587
    username: developweb2401@gmail.com
    password: yfnrtbhzjsyuxnph
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://lacvietquality.com:5433/postgres
    username: postgres
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC+7
      dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
  flyway:
    enabled: false
  profiles:
    active: deploy
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

springdoc:
  swagger-ui:
    path: swagger-ui.html
    operationsSorter: method

logging:
  level:
    org.springframework.security.web: DEBUG
