server:
  port: 8080
  forward-headers-strategy: framework
spring:
  security:
    user:
      name: admin
      password: 1234
  datasource:
    url: jdbc:postgresql://localhost:7777/oracle
    username: oracle
    password: oracle
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.O
  flyway:
    enabled: false
    driver-class-name: oracle.jdbc.driver.OracleDriver
  profiles:
    active: dev
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

springdoc:
  swagger-ui:
    path: swagger-ui.html
    operationsSorter: method