server:
  port: 5000
  forward-headers-strategy: framework
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 459707231919-ga493mkr3qj9a1lpaeli1f12pvdltv33.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  mail:
    host: smtp.gmail.com
    port: 587
    username: developweb2401@gmail.com
    password: yfnrtbhzjsyuxnph
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://dpg-chqbfundvk4goerbavn0-a.singapore-postgres.render.com:5432/plog
    username: vanphuc2401
    password: dn273FAZq6mt7FKd1SXnvNIzC1AqGDx6
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC+7
      dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
  flyway:
    enabled: false
  profiles:
    active: deploy
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
springdoc:
  swagger-ui:
    path: swagger-ui.html
    operationsSorter: method

aws:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: AKIATSCFT4H254V5AKOQ
  secretKey: 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
  bucketName: plog-resource
